FROM ubuntu:16.04

RUN DEBIAN_FRONTEND=noninteractive; apt-get update && apt-get upgrade -y && apt-get install -y --fix-missing gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm locales vim tmux tree man-db less sudo
RUN DEBIAN_FRONTEND=noninteractive; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN pip3 --no-cache-dir install gitpython Sphinx
RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8
