#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: swupdate-net <url>"
    return 1
fi

rootfs=$(mount | grep "on / type" | cut -d':' -f 2 | cut -d' ' -f 1)
if [ "$rootfs" = "/dev/mmcblk0p2" ]; then
    selection="stable,copy2"
elif [ "$rootfs" = "/dev/mmcblk0p3" ]; then
    selection="stable,copy1"
else
    echo "Invalid rootfs dev"
    return 1
fi

url="$1"

swupdate-progress -w -r &
swupdate -v -e $selection -d "-u $url"
