#!/bin/sh

# We do not want this
# set -e

# ASCII Font
#   ANSI Shadow

if [ -z "$NATURE_LINUX_BUILD_EXCLUDE_CETACEAN_IMAGE" ]; then
    (
        if [ -z "$NATURE_LINUX_BUILD_BORING" ]; then
            echo '                                                                   '
            echo ' ██████╗███████╗████████╗ █████╗  ██████╗███████╗ █████╗ ███╗   ██╗'
            echo '██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔════╝██╔══██╗████╗  ██║'
            echo '██║     █████╗     ██║   ███████║██║     █████╗  ███████║██╔██╗ ██║'
            echo '██║     ██╔══╝     ██║   ██╔══██║██║     ██╔══╝  ██╔══██║██║╚██╗██║'
            echo '╚██████╗███████╗   ██║   ██║  ██║╚██████╗███████╗██║  ██║██║ ╚████║'
            echo ' ╚═════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝'
            echo '-------------------------------------------------------------------'
        fi

        IMAGE=cetacean-image . ./setup
        bitbake cetacean-firmware
    )
fi

if [ -z "$NATURE_LINUX_BUILD_EXCLUDE_RODENT_IMAGE" ]; then
    (
        if [ -z "$NATURE_LINUX_BUILD_BORING" ]; then
            echo '                                                    '
            echo '██████╗  ██████╗ ██████╗ ███████╗███╗   ██╗████████╗'
            echo '██╔══██╗██╔═══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝'
            echo '██████╔╝██║   ██║██║  ██║█████╗  ██╔██╗ ██║   ██║   '
            echo '██╔══██╗██║   ██║██║  ██║██╔══╝  ██║╚██╗██║   ██║   '
            echo '██║  ██║╚██████╔╝██████╔╝███████╗██║ ╚████║   ██║   '
            echo '╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝   '
            echo '----------------------------------------------------'
        fi

        IMAGE=rodent-image . ./setup
        bitbake rodent-flasher-image
    )
fi

if [ -z "$NATURE_LINUX_BUILD_EXCLUDE_LIZARD_IMAGE" ]; then
    (
        if [ -z "$NATURE_LINUX_BUILD_BORING" ]; then
            echo '                                           '
            echo '██╗     ██╗███████╗ █████╗ ██████╗ ██████╗ '
            echo '██║     ██║╚══███╔╝██╔══██╗██╔══██╗██╔══██╗'
            echo '██║     ██║  ███╔╝ ███████║██████╔╝██║  ██║'
            echo '██║     ██║ ███╔╝  ██╔══██║██╔══██╗██║  ██║'
            echo '███████╗██║███████╗██║  ██║██║  ██║██████╔╝'
            echo '╚══════╝╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ '
            echo '-------------------------------------------'
        fi

        IMAGE=lizard-image . ./setup
        bitbake lizard-firmware
    )
fi
