#!/bin/sh

# We do not want this
# set -e

# ASCII Font
#   ANSI Shadow

NATURE_LINUX_BUILD_STATUS=0


if [ "$NATURE_LINUX_BUILD_EXCLUDE_CETACEAN_IMAGE" != "1" ]; then
    (
        if [ "$NATURE_LINUX_BUILD_BORING" != "1" ]; then
            echo '                                                                   '
            echo ' ██████╗███████╗████████╗ █████╗  ██████╗███████╗ █████╗ ███╗   ██╗'
            echo '██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔════╝██╔══██╗████╗  ██║'
            echo '██║     █████╗     ██║   ███████║██║     █████╗  ███████║██╔██╗ ██║'
            echo '██║     ██╔══╝     ██║   ██╔══██║██║     ██╔══╝  ██╔══██║██║╚██╗██║'
            echo '╚██████╗███████╗   ██║   ██║  ██║╚██████╗███████╗██║  ██║██║ ╚████║'
            echo ' ╚═════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝'
            echo '-------------------------------------------------------------------'
        fi

        IMAGE=cetacean-image . ./setup
        bitbake cetacean-firmware
    )
    if [ $? -ne 0 ]; then
        NATURE_LINUX_BUILD_STATUS=1
    fi
fi


if [ "$NATURE_LINUX_BUILD_EXCLUDE_RODENT_IMAGE" != "1" ]; then
    (
        if [ "$NATURE_LINUX_BUILD_BORING" != "1" ]; then
            echo '                                                    '
            echo '██████╗  ██████╗ ██████╗ ███████╗███╗   ██╗████████╗'
            echo '██╔══██╗██╔═══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝'
            echo '██████╔╝██║   ██║██║  ██║█████╗  ██╔██╗ ██║   ██║   '
            echo '██╔══██╗██║   ██║██║  ██║██╔══╝  ██║╚██╗██║   ██║   '
            echo '██║  ██║╚██████╔╝██████╔╝███████╗██║ ╚████║   ██║   '
            echo '╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝   '
            echo '----------------------------------------------------'
        fi

        IMAGE=rodent-image . ./setup
        bitbake rodent-flasher-image
    )
    if [ $? -ne 0 ]; then
        NATURE_LINUX_BUILD_STATUS=1
    fi
fi


if [ "$NATURE_LINUX_BUILD_EXCLUDE_LIZARD_IMAGE" != "1" ]; then
    (
        if [ "$NATURE_LINUX_BUILD_BORING" != "1" ]; then
            echo '                                           '
            echo '██╗     ██╗███████╗ █████╗ ██████╗ ██████╗ '
            echo '██║     ██║╚══███╔╝██╔══██╗██╔══██╗██╔══██╗'
            echo '██║     ██║  ███╔╝ ███████║██████╔╝██║  ██║'
            echo '██║     ██║ ███╔╝  ██╔══██║██╔══██╗██║  ██║'
            echo '███████╗██║███████╗██║  ██║██║  ██║██████╔╝'
            echo '╚══════╝╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ '
            echo '-------------------------------------------'
        fi

        IMAGE=lizard-image . ./setup
        bitbake lizard-firmware
    )
    if [ $? -ne 0 ]; then
        NATURE_LINUX_BUILD_STATUS=1
    fi
fi


if [ "$NATURE_LINUX_BUILD_EXCLUDE_MUSHROOM_IMAGE" != "1" ]; then
    (
        if [ "$NATURE_LINUX_BUILD_BORING" != "1" ]; then
            echo '                                                                         '
            echo '███╗   ███╗██╗   ██╗███████╗██╗  ██╗██████╗  ██████╗  ██████╗ ███╗   ███╗'
            echo '████╗ ████║██║   ██║██╔════╝██║  ██║██╔══██╗██╔═══██╗██╔═══██╗████╗ ████║'
            echo '██╔████╔██║██║   ██║███████╗███████║██████╔╝██║   ██║██║   ██║██╔████╔██║'
            echo '██║╚██╔╝██║██║   ██║╚════██║██╔══██║██╔══██╗██║   ██║██║   ██║██║╚██╔╝██║'
            echo '██║ ╚═╝ ██║╚██████╔╝███████║██║  ██║██║  ██║╚██████╔╝╚██████╔╝██║ ╚═╝ ██║'
            echo '╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚═╝'
            echo '-------------------------------------------------------------------------'
        fi

        IMAGE=mushroom-image . ./setup
        bitbake mushroom-firmware
    )
    if [ $? -ne 0 ]; then
        NATURE_LINUX_BUILD_STATUS=1
    fi
fi

exit $NATURE_LINUX_BUILD_STATUS
